### PR TITLE
Adding Nathan Phelps to MAINTAINERS.md

### PR DESCRIPTION
**Pull request by naphelps**
References:

Changes:
- Promoting Nathan Phelps to a maintainer of FDO-support.

### CODE REVIEW

**Review by joewxboy — APPROVED** [review]
THanks.  Do we need to remove Lorenzo?

**Review by bencourliss — CHANGES_REQUESTED** [review]
I would recommend removing Lorenzo since he's not actively working on the project anymore.

**Review by dlarson04 — APPROVED** [review]

**Comment by naphelps** [comment]
Lorenzo his told me he would like to keep all of his FDO roles in the community.

**Review by bencourliss — APPROVED** [review]

**Comment by joewxboy** [comment]
> Lorenzo his told me he would like to keep all of his FDO roles in the community.

That's great news.  @naphelps Do we have a new email address for Lorenzo?

**Comment by naphelps** [comment]
He is still with IBM.

**Pull request merged**
